name: GitHub Actions Demo
on: [push]
jobs:
  Check-python-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "src"
          strict: "low"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          pylint-options: "--rcfile=setup.cfg"
          isort-options: ""
          django: false